"""Sessions that ran before there was a ledger.

Docs: https://vedicreader.github.io/panjika/backfill.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_backfill.ipynb.

# %% auto #0
__all__ = ['SESSIONS', 'INJECTED', 'TOOL_PATHS', 'UNRESOLVED', 'sess_dir', 'read_recs', 'at_of', 'is_prompt', 'prompt_kind',
           'blocks', 'block_text', 'bash_paths', 'call_touches', 'bodies', 'usage_of', 'rec_id', 'transcript_plan',
           'apply_plan', 'backfill_file', 'backfill_session', 'backfill']

# %% ../nbs/06_backfill.ipynb #63e6de4b
import json, os, re, shlex
from datetime import datetime
from pathlib import Path

from fastcore.foundation import L

from .core import Home, hashed
from .harness import act, plan
from .write import action_for
from .write import Scribe

# %% ../nbs/06_backfill.ipynb #0bd028d0
SESSIONS = Path.home()/'.claude'/'projects'

def sess_dir(cwd=None, root=None):
    "The transcript folder for one project."
    if root: return Path(root)
    return SESSIONS/re.sub(r'[^a-zA-Z0-9]', '-', str(Path(cwd or '.').expanduser().resolve()))

def read_recs(path):
    "Records from a transcript, dropping a trailing line that is still being written."
    out = L()
    try: raw = Path(path).read_text(encoding='utf-8', errors='replace')
    except OSError: return out
    for line in raw.splitlines():
        if not line.strip(): continue
        try: out.append(json.loads(line))
        except ValueError: continue
    return out

def at_of(rec):
    "A record's epoch seconds. Claude Code writes ISO-8601 with a Z."
    t = (rec or {}).get('timestamp')
    if not t: return None
    try: return datetime.fromisoformat(str(t).replace('Z', '+00:00')).timestamp()
    except ValueError: return None

# %% ../nbs/06_backfill.ipynb #029c6fd2
INJECTED = ('<task-notification', '<system-reminder', '<wake ', '<local-command',
            '<command-name', '<user-prompt-submit-hook')

def is_prompt(rec):
    "A record that drove a turn: its message content is text rather than tool results."
    return rec.get('type') == 'user' and isinstance((rec.get('message') or {}).get('content'), str)

def prompt_kind(rec, text):
    "Whether a person typed this or the harness injected it. They are not otherwise tellable apart."
    kind = (rec.get('origin') or {}).get('kind') if isinstance(rec.get('origin'), dict) else None
    if kind and kind != 'human': return 'injected'
    return 'injected' if str(text).lstrip().startswith(INJECTED) else 'human'

def blocks(msg):
    "A message's content blocks, always as a list."
    c = (msg or {}).get('content')
    return [] if c is None else ([c] if isinstance(c, str) else list(c))

def block_text(content):
    "The plain text of content blocks. A tool result is a string or a list of blocks."
    if isinstance(content, str): return content
    out = []
    for b in (content if isinstance(content, list) else [content]):
        if isinstance(b, str): out.append(b)
        elif isinstance(b, dict) and b.get('type') == 'text': out.append(b.get('text') or '')
        elif isinstance(b, dict) and b.get('type') != 'thinking' and 'text' in b: out.append(str(b['text']))
    return '\n'.join(x for x in out if x)

# %% ../nbs/06_backfill.ipynb #785d6978
TOOL_PATHS = {
    'Edit': ('file_path', 'edit'), 'Write': ('file_path', 'create'),
    'MultiEdit': ('file_path', 'edit'), 'NotebookEdit': ('notebook_path', 'edit'),
    'Read': ('file_path', 'read'), 'NotebookRead': ('notebook_path', 'read'),
}

UNRESOLVED = ('$', '*', '?', '{', '}', '[', ']')
_HEREDOC = re.compile(r'(?:^|\s)<<-?\s*[\x27\x22]?(\w+)[\x27\x22]?\s*$')
_SEPS = ('|', '||', '&&', ';', '&')
_REDIR = ('>', '>>', '2>', '2>>', '&>', '&>>')

def _cmd_lines(cmd):
    "Command lines with heredoc bodies removed: a body is data, not shell syntax."
    out, lines, i = [], cmd.splitlines(), 0
    while i < len(lines):
        out.append(lines[i])
        if (m := _HEREDOC.search(lines[i])):
            marker = m.group(1); i += 1
            while i < len(lines) and lines[i].strip() != marker: i += 1
        i += 1
    return out

def _segments(line):
    "One line split at the shell operators, so a redirect belongs to the command it follows."
    try: toks = shlex.split(line, comments=True)
    except ValueError: return []
    segs, cur = [], []
    for t in toks:
        if t in _SEPS: segs.append(cur); cur = []
        else: cur.append(t)
    return [s for s in segs + [cur] if s]

def _named(p):
    "One candidate path, or None when it is not one this code can name."
    p = p.strip().strip('"').strip("'").rstrip(';&|')
    if not p or p in ('+', ';', '{}') or p.startswith(('-', '/dev/')): return None
    return None if any(c in p for c in UNRESOLVED) or p.isdigit() else p

def bash_paths(cmd):
    "Write targets a shell command obviously has. Conservative: a miss beats a guess."
    if not cmd: return []
    out = []
    for line in _cmd_lines(cmd):
        for seg in _segments(line):
            if seg[0] in ('[[', '[', 'test'): continue
            for i, t in enumerate(seg):
                if t in _REDIR and i + 1 < len(seg): out.append(seg[i+1])
                elif len(t) > 1 and t[0] == '>' and t[1] != '&': out.append(t.lstrip('>'))
                elif len(t) > 2 and t[:2] in ('2>', '&>') and not t[2:].lstrip('>').startswith('&'):
                    out.append(t[2:].lstrip('>'))
            if seg[0] == 'tee':
                rest = [t for t in seg[1:] if not t.startswith('-')]
                if rest: out.append(rest[0])
            elif seg[0] == 'sed' and any(t == '-i' or t.startswith('-i.') for t in seg[1:]):
                out += [t for t in seg[1:] if not t.startswith('-')][1:]
    seen = []
    for p in map(_named, out):
        if p and p not in seen: seen.append(p)
    return seen

def call_touches(tool, args, result=None):
    "`[(path, action)]` for one call. Empty when the tool moved no file this code can name."
    args, out = args or {}, []
    if tool in TOOL_PATHS:
        key, action = TOOL_PATHS[tool]
        if (p := args.get(key)): out.append((p, action))
    if isinstance(result, dict):
        for key in ('filePath', 'file_path', 'notebook_path'):
            if (p := result.get(key)) and not any(p == q for q, _ in out):
                out.append((p, 'read' if tool in ('Read', 'NotebookRead') else 'edit'))
    if tool == 'Bash': out += [(p, 'edit') for p in bash_paths(args.get('command'))]
    return out

def bodies(tool, args, result):
    "The before and after bodies of a write, when the transcript actually carries them."
    args, result = args or {}, result if isinstance(result, dict) else {}
    before, after = result.get('originalFile'), result.get('newFile')
    if after is None and tool == 'Write': after = args.get('content')
    return before, after

# %% ../nbs/06_backfill.ipynb #a57f7a5d
def usage_of(recs):
    "Tokens over assistant records, counting each API response once however it was split."
    seen, tot = set(), dict(input=0, output=0, cache=0)
    for r in recs:
        if r.get('type') != 'assistant': continue
        m = r.get('message') or {}
        mid = m.get('id') or r.get('requestId') or r.get('uuid')
        if mid in seen: continue
        seen.add(mid)
        u = m.get('usage') or {}
        tot['input']  += u.get('input_tokens') or 0
        tot['output'] += u.get('output_tokens') or 0
        tot['cache']  += (u.get('cache_read_input_tokens') or 0) + (u.get('cache_creation_input_tokens') or 0)
    return tot

def rec_id(*parts):
    "A record id derived from the transcript, so re-reading it writes the same record."
    return 'b' + hashed('\x1f'.join(str(p) for p in parts), 22)


def transcript_plan(recs, session='', agent='', meta=None, harness='claude-code'):
    "One transcript as a plan of `Scribe` calls, in time order."
    recs = sorted(recs, key=lambda r: (at_of(r) or 0))
    first = next((r for r in recs if r.get('sessionId')), {})
    sid = session or first.get('sessionId') or ''
    cwd = next((r.get('cwd') for r in recs if r.get('cwd')), '')
    model = next(((r.get('message') or {}).get('model') for r in recs
                  if r.get('type') == 'assistant' and (r.get('message') or {}).get('model')), '')
    p = plan(f'{sid}:{agent}' if agent else sid, cwd)
    if not recs: return p
    stamps = [t for t in (at_of(r) for r in recs) if t]
    first_at, last_at = (stamps[0], stamps[-1]) if stamps else (None, None)
    act(p, 'begin', harness=harness, model=str(model or ''), agent=agent,
        parent=sid if agent else '', title=str((meta or {}).get('description') or ''),
        at=first_at, started=first_at, id=rec_id('begin', p.session))
    results = {b.get('tool_use_id'): (b, r) for r, b in _tool_blocks(recs)
               if b.get('type') == 'tool_result'}
    opened = False
    for r in recs:
        if is_prompt(r):
            text = r['message']['content']
            act(p, 'write', kind='session', prompt=text[:2000],
                origin=('agent' if agent else prompt_kind(r, text)), at=at_of(r),
                id=rec_id('prompt', p.session, r.get('uuid') or text[:80]))
            opened = True
            continue
        m = r.get('message')
        if not isinstance(m, dict): continue
        if not opened and (r.get('type') == 'assistant' or _has_tool(m)):
            act(p, 'note', text='resumed: the prompt for this work is not in this transcript',
                at=at_of(r), id=rec_id('resumed', p.session))
            opened = True
        _call_acts(p, r, m, results, p.session)
    u = usage_of(recs)
    act(p, 'end', status='imported', at=last_at, ended=last_at, id=rec_id('end', p.session),
        input=u['input'], output=u['output'], cache=u['cache'])
    return p

def _tool_blocks(recs):
    for r in recs:
        m = r.get('message')
        if isinstance(m, dict):
            for b in blocks(m):
                if isinstance(b, dict): yield r, b

def _has_tool(m):
    return any(isinstance(b, dict) and b.get('type') == 'tool_use' for b in blocks(m))

def _call_acts(p, rec, msg, results, sid=''):
    "One record's tool calls, with their results and whatever files they moved."
    for b in blocks(msg):
        if not isinstance(b, dict) or b.get('type') != 'tool_use': continue
        res, rrec = results.get(b.get('id'), (None, None))
        payload = (rrec or {}).get('toolUseResult') if rrec else None
        payload = payload if isinstance(payload, dict) else None
        ok = not (res or {}).get('is_error')
        tool, args = str(b.get('name') or ''), (b.get('input') or {})
        tid = b.get('id') or f"{rec.get('uuid')}:{tool}"
        started, done = at_of(rec), at_of(rrec)
        act(p, 'step', tool=tool, target=_target_of(args), ok=ok, at=started,
            args=args, output=block_text((res or {}).get('content')) if res else '',
            id=rec_id('step', sid, tid), action=action_for(tool),
            secs=round(done - started, 2) if started and done else 0.0,
            summary='' if res else 'the call had not returned when this was read')
        if not (ok and res): continue
        before, after = bodies(tool, args, payload)
        for path, action in call_touches(tool, args, payload):
            if action == 'read': continue
            kw = dict(before=before, after_text=after) if after is not None else {}
            act(p, 'touch', path=path, action=action, at=at_of(rec),
                id=rec_id('touch', sid, tid, path), **kw)

def _target_of(args):
    for k in ('file_path', 'notebook_path', 'path', 'command', 'pattern', 'description'):
        if (v := (args or {}).get(k)): return str(v)[:160]
    return''

# %% ../nbs/06_backfill.ipynb #6e329335
def apply_plan(p, home=None, start=None):
    "Run a plan against a ledger. Returns the number of records written."
    if not p.acts: return 0
    where = (p.start or start) if home is None else (start or p.start)
    sc = Scribe(home=home, session=p.session, start=where or '.')
    if not sc.home.exists: sc.home.init()
    for a in p.acts:
        a = dict(a); do = a.pop('do')
        if do == 'begin': getattr(sc, do)(**a); continue
        try: getattr(sc, do)(**a)
        except Exception: continue
    return len(p.acts)

def backfill_file(path, home=None, start=None, agent='', meta=None):
    "One transcript into the ledger. Returns `(session, records written)`."
    recs = read_recs(path)
    if not recs: return None, 0
    p = transcript_plan(recs, agent=agent, meta=meta)
    return p.session, apply_plan(p, home, start)

def backfill_session(path, home=None, start=None):
    "A transcript and every subagent transcript beside it."
    path = Path(path)
    out = [backfill_file(path, home, start)]
    subs = path.parent/path.stem/'subagents'
    for f in sorted(subs.glob('*.jsonl')) if subs.is_dir() else []:
        meta = None
        mp = f.with_suffix('.meta.json')
        if mp.exists():
            try: meta = json.loads(mp.read_text())
            except ValueError: meta = None
        out.append(backfill_file(f, home, start, agent=f.stem, meta=meta))
    return [(s, n) for s, n in out if s]

def backfill(cwd=None, root=None, home=None, start=None, limit=0):
    "Every Claude Code transcript for one project, or for every project."
    d = sess_dir(cwd, root)
    files = sorted(d.glob('*.jsonl')) if (cwd or root) else sorted(SESSIONS.glob('*/*.jsonl'))
    if limit: files = files[-int(limit):]
    out = []
    for f in files:
        try: out += backfill_session(f, home, start)
        except Exception: continue
    return out
