"""Where a ledger lives, what a record is, and how a line gets onto disk.

Docs: https://vedicreader.github.io/panjika/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['KINDS', 'LEDGER', 'DETAIL', 'DIR', 'MAX_LINE', 'MAX_DETAIL', 'GITATTRIBUTES', 'GITIGNORE', 'dumps', 'loads', 'now',
           'new_id', 'hashed', 'file_hash', 'git_root', 'find_home', 'Home', 'clip', 'append', 'read_shard', 'records',
           'fold']

# %% ../nbs/00_core.ipynb #8e10346a
import hashlib, os, time, uuid
from pathlib import Path

import orjson
from fastcore.basics import AttrDict, ifnone
from fastcore.foundation import L

# %% ../nbs/00_core.ipynb #ff2888ec
#: The record kinds. A line whose `kind` is not one of these is skipped by every reader here,
#: so a newer writer can add a kind without breaking an older reader.
KINDS = ('session', 'step', 'touch', 'commit', 'note')

#: Where a ledger keeps its two tiers, relative to the ledger folder.
LEDGER, DETAIL = 'ledger', 'detail'

#: The folder name a ledger takes, in a repository or in the home directory.
DIR = '.panjika'

#: One committed line, capped. A ledger row is a summary; anything longer belongs in `detail`.
MAX_LINE = 16_000

#: One detail line. Large, because a tool result belongs here whole, but not unbounded.
MAX_DETAIL = 400_000

# %% ../nbs/00_core.ipynb #d976f85e
def dumps(rec):
    "One record as the bytes of a line, newline included."
    return orjson.dumps(rec, option=orjson.OPT_SORT_KEYS) + b'\n'


def loads(line):
    "One line as a record, or `None` when the line is not a JSON object."
    try: rec = orjson.loads(line)
    except orjson.JSONDecodeError: return None
    return AttrDict(rec) if isinstance(rec, dict) else None

# %% ../nbs/00_core.ipynb #403e34f0
def now(): return round(time.time(), 3)


def new_id(prefix=''):
    "A short unique id. Records carry one so a union merge can be deduplicated."
    return f'{prefix}{uuid.uuid4().hex[:12]}'


def hashed(data, n=16):
    "A short content hash. Used for file contents and for the text of a changed line."
    if isinstance(data, str): data = data.encode('utf-8', 'replace')
    return hashlib.blake2b(data, digest_size=n // 2).hexdigest()


def file_hash(path):
    "The hash of a file's bytes, or `''` when it is not there."
    try: return hashed(Path(path).read_bytes())
    except OSError: return ''

# %% ../nbs/00_core.ipynb #b6b5f0ce
def git_root(start='.'):
    "The repository `start` is inside, or `None`."
    try:
        from gheasy.repo import repo_root
        root = repo_root(str(start))
        return None if root is None else Path(root)
    except Exception: return None


def find_home(start='.'):
    "The ledger folder for `start`: an existing one above it, else its repository, else `~`."
    here = Path(start).resolve()
    for d in (here, *here.parents):
        if (d/DIR).is_dir(): return d/DIR
    root = git_root(here)
    return (root or Path.home())/DIR

# %% ../nbs/00_core.ipynb #2135323a
GITATTRIBUTES = """# Append-only. Take both sides of a merge; readers deduplicate by record id.
ledger/*.jsonl merge=union
"""

GITIGNORE = """# Machine-local: whole tool arguments, whole outputs, exact changed lines.
detail/
"""


class Home:
    "One ledger folder, and the shards inside it."

    def __init__(self, path=None, start='.'):
        self.path = Path(path) if path else find_home(start)
        self.root = self.path.parent

    def __repr__(self): return f'Home({self.path})'
    def __eq__(self, other): return isinstance(other, Home) and self.path == other.path

    def dir(self, tier): return self.path/tier

    def shard(self, tier=LEDGER, at=None):
        "The file a record written at `at` belongs in."
        stamp = time.strftime('%Y-%m', time.localtime(at if at else now()))
        return self.dir(tier)/f'{stamp}.jsonl'

    def shards(self, tier=LEDGER):
        "Every shard of one tier, oldest first."
        d = self.dir(tier)
        return sorted(d.glob('*.jsonl')) if d.is_dir() else []

    @property
    def exists(self): return self.path.is_dir()

    def init(self):
        "Make the folder and the two dotfiles that let the ledger tier be committed. Idempotent."
        for tier in (LEDGER, DETAIL): self.dir(tier).mkdir(parents=True, exist_ok=True)
        (self.path/'.gitattributes').write_text(GITATTRIBUTES)
        (self.path/'.gitignore').write_text(GITIGNORE)
        return self

# %% ../nbs/00_core.ipynb #2ca439e4
def clip(rec, limit):
    "Shorten a record until its line fits, longest string field first."
    line = dumps(rec)
    if len(line) <= limit: return rec, len(line)
    rec = dict(rec)
    for k in sorted((k for k, v in rec.items() if isinstance(v, str)),
                    key=lambda k: len(rec[k]), reverse=True):
        over = len(dumps(rec)) - limit
        if over <= 0: break
        keep = max(0, len(rec[k]) - over - 32)
        rec[k] = rec[k][:keep] + f'... [clipped {len(rec[k]) - keep} chars]' if keep else ''
    return rec, len(dumps(rec))


def append(path, rec, limit=MAX_LINE):
    "Write one record as one line. Returns the record as it was written."
    rec, _ = clip(rec, limit)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    try: os.write(fd, dumps(rec))
    finally: os.close(fd)
    return AttrDict(rec)

# %% ../nbs/00_core.ipynb #8c4b425b
def read_shard(path):
    "Every readable record in one shard."
    out = L()
    try: raw = Path(path).read_bytes()
    except OSError: return out
    for line in raw.splitlines():
        if not line.strip(): continue
        rec = loads(line)
        if rec is not None and rec.get('kind') in KINDS and rec.get('id'): out.append(rec)
    return out


def records(home, tier=LEDGER):
    "Every record in a tier, oldest first, deduplicated by id."
    seen, out = set(), L()
    for shard in home.shards(tier):
        for rec in read_shard(shard):
            if rec.id in seen: continue
            seen.add(rec.id)
            out.append(rec)
    return out.sorted(key=lambda r: r.get('at') or 0)

# %% ../nbs/00_core.ipynb #eb0a0ee1
def fold(recs, key='session', first=()):
    """Merge records sharing `key` into one row each, later values winning.

    A blank later value never erases an earlier one, so a hook that knows only half the facts
    can append what it knows without wiping what another harness already recorded.

    A field named in `first` keeps its earliest value instead. A session's opening ask is what
    it was for, and a session is described by one record per prompt, so letting the last one
    win headlines a long session with whatever was said to it most recently.
    """
    out, held = {}, {}
    for rec in recs:
        k = rec.get(key)
        if not k: continue
        row = out.setdefault(k, AttrDict(rec))
        for name, v in rec.items():
            if v is None or v == '' or name == 'id': continue
            if name in first:
                if (k, name) in held: continue
                held[(k, name)] = True
            row[name] = v
    return L(out.values())
