"""a record, the file it is written to, and how it reads back

Docs: https://vedicreader.github.io/panjika/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['KINDS', 'LEDGER', 'DETAIL', 'DIR', 'MAX_LINE', 'MAX_DETAIL', 'GITATTRIBUTES', 'GITIGNORE', 'ACTION_HINTS', 'ACTIONS',
           'OPENING', 'dumps', 'loads', 'now', 'new_id', 'hashed', 'file_hash', 'git_root', 'find_home', 'Home', 'clip',
           'append', 'read_shard', 'records', 'fold', 'action_for', 'Scribe', 'repo_facts', 'text_changes',
           'diff_lines', 'body_lines', 'head_hash', 'shard_stamp', 'Ledger', 'asks', 'headline', 'counters']

# %% ../nbs/00_core.ipynb #4d732c15
import hashlib, os, time, uuid
from pathlib import Path

import orjson
from fastcore.basics import AttrDict, patch
from fastcore.foundation import L
from gheasy.repo import GitRepo

# %% ../nbs/00_core.ipynb #30ad0d01
KINDS = ('session', 'step', 'touch', 'commit', 'note')
LEDGER, DETAIL = 'ledger', 'detail'
DIR = '.panjika'
MAX_LINE = 16_000
MAX_DETAIL = 400_000

# %% ../nbs/00_core.ipynb #1f149f7f
def dumps(rec):
    "One record as the bytes of a line, newline included."
    return orjson.dumps(rec, option=orjson.OPT_SORT_KEYS) + b'\n'


def loads(line):
    "One line as a record, or `None` when the line is not a JSON object."
    try: rec = orjson.loads(line)
    except orjson.JSONDecodeError: return None
    return AttrDict(rec) if isinstance(rec, dict) else None

# %% ../nbs/00_core.ipynb #263e0118
def now(): return round(time.time(), 3)


def new_id(prefix=''):
    "A short unique id. Records carry one so a union merge can be deduplicated."
    return f'{prefix}{uuid.uuid4().hex[:12]}'


def hashed(data, n=16):
    "A short content hash, for file contents and for the text of a changed line."
    if isinstance(data, str): data = data.encode('utf-8', 'replace')
    return hashlib.blake2b(data, digest_size=n // 2).hexdigest()


def file_hash(path):
    "The hash of a file's bytes, or `''` when it is not there."
    try: return hashed(Path(path).read_bytes())
    except OSError: return ''

# %% ../nbs/00_core.ipynb #ec4bcf60
def git_root(start='.'):
    "The repository `start` is inside, or `None`."
    try:
        from gheasy.repo import repo_root
        root = repo_root(str(start))
        return None if root is None else Path(root)
    except Exception: return None


def find_home(start='.'):
    "The ledger folder for `start`: an existing one above it, else its repository, else `~`."
    here = Path(start).resolve()
    for d in (here, *here.parents):
        if (d/DIR).is_dir(): return d/DIR
    root = git_root(here)
    return (root or Path.home())/DIR

# %% ../nbs/00_core.ipynb #bbbce8ca
GITATTRIBUTES = """# Append-only. Take both sides of a merge; readers deduplicate by record id.
ledger/*.jsonl merge=union
"""

GITIGNORE = """# Machine-local: whole tool arguments, whole outputs, exact changed lines.
detail/
"""


class Home:
    "One ledger folder, and the shards inside it."

    def __init__(self, path=None, start='.'):
        self.path = Path(path) if path else find_home(start)
        self.root = self.path.parent

    def __repr__(self): return f'Home({self.path})'
    def __eq__(self, other): return isinstance(other, Home) and self.path == other.path

    def dir(self, tier): return self.path/tier

    def shard(self, tier=LEDGER, at=None):
        "The file a record written at `at` belongs in."
        stamp = time.strftime('%Y-%m', time.localtime(at if at else now()))
        return self.dir(tier)/f'{stamp}.jsonl'

    def shards(self, tier=LEDGER):
        "Every shard of one tier, oldest first."
        d = self.dir(tier)
        return sorted(d.glob('*.jsonl')) if d.is_dir() else []

    @property
    def exists(self): return self.path.is_dir()

    def init(self):
        "Make the folder and the two dotfiles that let the ledger tier be committed. Idempotent."
        for tier in (LEDGER, DETAIL): self.dir(tier).mkdir(parents=True, exist_ok=True)
        (self.path/'.gitattributes').write_text(GITATTRIBUTES)
        (self.path/'.gitignore').write_text(GITIGNORE)
        return self

# %% ../nbs/00_core.ipynb #2d9ce6c1
def clip(rec, limit):
    "Shorten a record until its line fits, longest string field first."
    line = dumps(rec)
    if len(line) <= limit: return rec, len(line)
    rec = dict(rec)
    for k in sorted((k for k, v in rec.items() if isinstance(v, str)),
                    key=lambda k: len(rec[k]), reverse=True):
        over = len(dumps(rec)) - limit
        if over <= 0: break
        keep = max(0, len(rec[k]) - over - 32)
        rec[k] = rec[k][:keep] + f'... [clipped {len(rec[k]) - keep} chars]' if keep else ''
    return rec, len(dumps(rec))


def append(path, rec, limit=MAX_LINE):
    "Write one record as one line. Returns the record as it was written."
    rec, _ = clip(rec, limit)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    try: os.write(fd, dumps(rec))
    finally: os.close(fd)
    return AttrDict(rec)

# %% ../nbs/00_core.ipynb #8b435837
def read_shard(path):
    "Every readable record in one shard."
    out = L()
    try: raw = Path(path).read_bytes()
    except OSError: return out
    for line in raw.splitlines():
        if not line.strip(): continue
        rec = loads(line)
        if rec is not None and rec.get('kind') in KINDS and rec.get('id'): out.append(rec)
    return out


def records(home, tier=LEDGER):
    "Every record in a tier, oldest first, deduplicated by id."
    seen, out = set(), L()
    for shard in home.shards(tier):
        for rec in read_shard(shard):
            if rec.id in seen: continue
            seen.add(rec.id)
            out.append(rec)
    return out.sorted(key=lambda r: r.get('at') or 0)

# %% ../nbs/00_core.ipynb #b17a3aa6
def fold(recs, key='session', first=()):
    "Merge records sharing `key` into one row each, later values winning and `first` fields keeping their earliest."
    out, held = {}, {}
    for rec in recs:
        k = rec.get(key)
        if not k: continue
        row = out.setdefault(k, AttrDict(rec))
        for name, v in rec.items():
            if v is None or v == '' or name == 'id': continue
            if name in first:
                if (k, name) in held: continue
                held[(k, name)] = True
            row[name] = v
    return L(out.values())

# %% ../nbs/00_core.ipynb #fca4710d
ACTION_HINTS = (
    ('write', ('edit', 'write', 'patch', 'create', 'apply', 'update', 'insert', 'replace', 'delete')),
    ('run',   ('bash', 'shell', 'exec', 'run', 'terminal', 'command', 'python', 'notebook_run')),
    ('net',   ('web', 'fetch', 'url', 'browser', 'http', 'research', 'crawl')),
    ('search',('grep', 'search', 'glob', 'find', 'index', 'similar', 'outline', 'symbols')),
    ('read',  ('read', 'view', 'cat', 'open', 'ls', 'list', 'show', 'inspect', 'vars')),
    ('plan',  ('todo', 'plan', 'task')),
    ('ask',   ('ask', 'approval', 'question', 'permission')),
)

ACTIONS = ('write', 'run', 'net', 'search', 'read', 'plan', 'ask', 'other')


def action_for(tool):
    "Which of `ACTIONS` a tool name means. `other` when nothing matches."
    name = str(tool or '').lower()
    for action, hints in ACTION_HINTS:
        if any(h in name for h in hints): return action
    return 'other'

# %% ../nbs/00_core.ipynb #b4122dcc
def _target(value, n=160):
    "The one-line target of a step: a path, a command, a url, whatever it was pointed at."
    return ' '.join(str(value or '').split())[:n]


class Scribe:
    "Appends to one ledger."

    def __init__(self,
                 home=None,         # the ledger folder. None finds one from `start`
                 session='',        # the session every record joins. None starts a fresh id
                 start='.',         # where to look for a ledger, and the repository to describe
                 detail=True):      # write the machine-local tier as well as the committed one
        self.home = home if isinstance(home, Home) else Home(home, start)
        self.session = str(session or new_id('s-'))
        self.start, self.detail = str(start), bool(detail)
        self._seq = 0

    def __repr__(self): return f'Scribe({self.session} -> {self.home.path})'

    def write(self, kind, detail=None, **fields):
        "Append one record. `detail` goes to the machine-local tier under the same id."
        rec = {'kind': kind, 'id': fields.pop('id', None) or new_id(),
               'at': fields.pop('at', None) or now(),
               'session': fields.pop('session', None) or self.session, **fields}
        rec = {k: v for k, v in rec.items() if v is not None}
        out = append(self.home.shard(LEDGER, rec['at']), rec)
        if detail and self.detail:
            append(self.home.shard(DETAIL, rec['at']),
                   {'kind': kind, 'id': rec['id'], 'at': rec['at'], 'session': rec['session'], **detail},
                   MAX_DETAIL)
        return out

# %% ../nbs/00_core.ipynb #32f91910
def repo_facts(start='.'):
    "The repository name, root and current branch for `start`, as far as they can be told."
    root = git_root(start)
    branch = ''
    if root is not None:
        try: branch = GitRepo(root).run('rev-parse', '--abbrev-ref', 'HEAD').strip()
        except Exception: branch = ''
    return {'repo': root.name if root else '', 'root': str(root) if root else '',
            'branch': '' if branch == 'HEAD' else branch}

# %% ../nbs/00_core.ipynb #6086d813
@patch
def begin(self:Scribe, harness, model='', prompt='', title='', parent='', agent='', **fields):
    "Record that a session started. Returns its id."
    self.write('session', harness=str(harness), model=str(model or ''),
               prompt=_target(prompt, 2000), title=str(title or ''), status='open',
               parent=str(parent or ''), agent=str(agent or ''),
               started=fields.pop('started', None) or fields.get('at') or now(),
               cwd=str(Path(self.start).resolve()), **repo_facts(self.start), **fields)
    return self.session


@patch
def end(self:Scribe, status='done', **fields):
    "Record that a session finished, with whatever counters the harness can supply."
    return self.write('session', status=str(status),
                      ended=fields.pop('ended', None) or fields.get('at') or now(), **fields)

# %% ../nbs/00_core.ipynb #903b5940
@patch
def step(self:Scribe, tool, target='', ok=True, secs=0.0, action='', summary='',
         args=None, output=None, **fields):
    "Record one tool call. Returns the step id."
    self._seq += 1
    detail = None
    if args is not None or output is not None:
        detail = {'tool': str(tool), 'args': args, 'output': None if output is None else str(output)}
    rec = self.write('step', detail=detail, tool=str(tool), seq=self._seq,
                     action=action or action_for(tool), target=_target(target),
                     ok=bool(ok), secs=round(float(secs or 0), 3),
                     summary=_target(summary, 300), **fields)
    return rec.id


@patch
def note(self:Scribe, text, **fields):
    "Record a line of prose against the session: a plan, a summary, a reason."
    return self.write('note', text=str(text)[:4000], **fields).id

# %% ../nbs/00_core.ipynb #4afcdb4e
def text_changes(before, after):
    "The lines `after` adds to `before` and the ones it drops, for a change git cannot be asked about."
    import difflib
    b, a = (before or '').splitlines(), (after or '').splitlines()
    add, rem = [], []
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, b, a).get_opcodes():
        if tag in ('replace', 'delete'): rem += b[i1:i2]
        if tag in ('replace', 'insert'): add += a[j1:j2]
    return add, rem


def diff_lines(diff):
    "The added and removed lines of a unified diff, without its headers."
    added, removed = [], []
    for line in str(diff or '').splitlines():
        if line[:4] in ('+++ ', '--- ') or line in ('+++', '---'): continue
        if line.startswith('+'): added.append(line[1:])
        elif line.startswith('-'): removed.append(line[1:])
    return added, removed


def body_lines(path):
    "Every line of a file, for a change git will not diff because it is not tracking it."
    try: return Path(path).read_text(encoding='utf-8', errors='replace').splitlines()
    except OSError: return []


def head_hash(root, path):
    "The hash of a path's committed content at HEAD, or `''` when it is not committed."
    try: return hashed(GitRepo(root).run('show', f'HEAD:{path}'))
    except Exception: return ''

# %% ../nbs/00_core.ipynb #9cc92da4
@patch
def touch(self:Scribe,
          path,               # the file that moved, absolute or relative to `start`
          action='edit',      # what happened to it: edit, create, delete
          step='',            # the id of the step that did it
          before=None,        # the body before the change, for a backfill
          after_text=None,    # the body after it, for a backfill
          **fields):
    "Record that a file was touched, and how it now differs from `HEAD`."
    p = Path(path)
    root = git_root(p if p.is_absolute() else self.start)
    rel = str(p.resolve().relative_to(root)) if root and p.is_absolute() else str(path)
    ranges, added, removed, tracked = [], [], [], bool(root)
    if after_text is not None:
        added, removed = text_changes(before, after_text)
    elif root is not None:
        try:
            ch = GitRepo(root).file_changes(rel)
            ranges = [[r['from'], r['to'], r['kind']] for r in ch.get('ranges') or []]
            added, removed = diff_lines(ch.get('diff'))
            tracked = not (ch.get('status') or {}).get('untracked', False)
        except Exception: pass
    if not added and not tracked and root is not None:
        added = body_lines(p if p.is_absolute() else Path(self.start)/path)
    detail = {'path': rel, 'lines': [hashed(t) for t in added][:2000]} if added else None
    rec = self.write('touch', detail=detail, path=rel, action=str(action), step=str(step or ''),
                     head=head_hash(root, rel) if root else '',
                     after=(hashed(after_text) if after_text is not None else
                            file_hash(p if p.is_absolute() else Path(self.start)/path)),
                     added=len(added), removed=len(removed), ranges=ranges[:200],
                     tracked=tracked, **fields)
    return rec.id


@patch
def commit(self:Scribe, sha, subject='', author='', files=(), branch='', **fields):
    "Record that a commit exists and which session it belongs to."
    return self.write('commit', sha=str(sha), subject=_target(subject, 300), author=str(author or ''),
                      files=list(files)[:500], branch=str(branch or ''), **fields).id

# %% ../nbs/00_core.ipynb #ac665163
def shard_stamp(home, tier=LEDGER):
    "What changes when a shard does. The cache key."
    out = []
    for p in home.shards(tier):
        try: st = p.stat()
        except OSError: continue
        out.append((p.name, st.st_size, st.st_mtime_ns))
    return tuple(out)


class Ledger:
    "One ledger, read. Rereads a tier when a shard on disk has changed."

    def __init__(self, home=None, start='.'):
        self.home = home if isinstance(home, Home) else Home(home, start)
        self._cache, self._stamps = {}, {}

    def __repr__(self): return f'Ledger({self.home.path}, {len(self.all())} records)'

    @property
    def exists(self): return self.home.exists

    def all(self, tier=LEDGER):
        "Every record in a tier, oldest first."
        stamp = shard_stamp(self.home, tier)
        if self._stamps.get(tier) != stamp:
            self._cache[tier], self._stamps[tier] = records(self.home, tier), stamp
        return self._cache[tier]

    def of(self, kind, tier=LEDGER):
        "Every record of one kind."
        return self.all(tier).filter(lambda r: r.kind == kind)

# %% ../nbs/00_core.ipynb #4e6dfcd5
OPENING = ('prompt', 'started')


def asks(recs, sid):
    "Every prompt put to one session, in order, each with where it came from."
    return [(r.prompt, r.get('origin') or 'human') for r in recs
            if r.get('session') == sid and r.get('prompt')]


def headline(asked):
    "What a session was for: the first thing a person asked it."
    return next((p for p, o in asked if o != 'injected'), asked[0][0] if asked else '')


def counters(steps):
    "What a session's steps add up to: how many worked, how many did not, and which tools."
    ok = sum(1 for s in steps if s.get('ok', True))
    tools, actions = {}, {}
    for s in steps:
        tools[s.get('tool', '?')] = tools.get(s.get('tool', '?'), 0) + 1
        actions[s.get('action', 'other')] = actions.get(s.get('action', 'other'), 0) + 1
    return {'n_steps': len(steps), 'steps_ok': ok, 'steps_fail': len(steps) - ok,
            'secs': round(sum(float(s.get('secs') or 0) for s in steps), 2),
            'tools': dict(sorted(tools.items(), key=lambda kv: -kv[1])),
            'actions': dict(sorted(actions.items(), key=lambda kv: -kv[1]))}


def _since(value):
    "Seconds since the epoch for `7d`, `12h`, `30m`, a count of days, or a timestamp."
    if value in (None, ''): return 0
    if isinstance(value, (int, float)) and value > 10_000_000: return float(value)
    text = str(value).strip().lower()
    units = {'d': 86400, 'h': 3600, 'm': 60, 'w': 604800, 's': 1}
    n, unit = (text[:-1], text[-1]) if text[-1:] in units else (text, 'd')
    try: return time.time() - float(n) * units[unit]
    except ValueError: return 0

# %% ../nbs/00_core.ipynb #e4b7d3fe
@patch
def sessions(self:Ledger, limit=20, harness='', since='', repo='', path='', status=''):
    "Session rows, newest first. Every filter is optional and they compose."
    recs = self.of('session')
    rows = fold(recs, first=OPENING)
    for r in rows:
        if (asked := asks(recs, r.session)): r.prompt = headline(asked)
    if path: rows = rows.filter(lambda r: r.session in self.sessions_touching(path))
    for field, want in (('harness', harness), ('repo', repo), ('status', status)):
        if want: rows = rows.filter(lambda r, f=field, w=want: r.get(f) == w)
    if since:
        after = _since(since)
        rows = rows.filter(lambda r: (r.get('started') or r.get('at') or 0) >= after)
    rows = rows.sorted(key=lambda r: r.get('started') or r.get('at') or 0, reverse=True)
    return rows if not limit else rows[:int(limit)]


@patch
def sessions_touching(self:Ledger, path):
    "The ids of every session that touched `path`."
    p = str(path)
    return {r.session for r in self.of('touch') if r.get('path') == p}

# %% ../nbs/00_core.ipynb #ba3ee683
@patch
def files(self:Ledger, session):
    "What one session did to each file it touched, one row per path."
    out = {}
    for r in self.of('touch'):
        if r.session == session: out[r.path] = r
    return L(out.values()).sorted(key=lambda r: r.path)


@patch
def session(self:Ledger, sid):
    "One session, with everything recorded against it."
    recs = self.of('session')
    rows = fold(recs, first=OPENING).filter(lambda r: r.session == sid)
    row = AttrDict(rows[0]) if rows else AttrDict(kind='session', session=sid, id=sid)
    asked = asks(recs, sid)
    row['prompts'] = L(asked)
    row['prompt'] = headline(asked) if asked else row.get('prompt', '')
    row['last_prompt'] = asked[-1][0] if asked else ''
    for kind in ('step', 'touch', 'commit', 'note'):
        row[f'{kind}s'] = self.of(kind).filter(lambda r: r.session == sid).sorted(
            key=lambda r: r.get('at') or 0)
    row['files'] = self.files(sid)
    row.update(counters(row.steps))
    began = row.get('started') or row.get('at') or 0
    row['seconds'] = round((row.get('ended') or row.get('at') or 0) - began, 1) if began else 0.0
    return row

# %% ../nbs/00_core.ipynb #bf3363a3
@patch
def trail(self:Ledger, path, limit=50):
    "Every session that touched `path`, newest first, with its touch of that file."
    p, out = str(path), []
    by_session = {}
    for r in self.of('touch'):
        if r.get('path') == p: by_session[r.session] = r
    rows = {r.session: r for r in fold(self.of('session'))}
    commits = {}
    for c in self.of('commit'):
        if p in (c.get('files') or ()): commits.setdefault(c.session, []).append(c)
    for sid, touch in by_session.items():
        row = AttrDict(rows.get(sid) or {'kind': 'session', 'session': sid, 'id': sid})
        out.append(AttrDict(row, touch=touch, commits=L(commits.get(sid) or []),
                            at=touch.get('at') or row.get('at') or 0))
    out = L(out).sorted(key=lambda r: r.at, reverse=True)
    return out if not limit else out[:int(limit)]


@patch
def touched(self:Ledger, since='', limit=200):
    "Every path the ledger knows about, most recently touched first."
    after, seen = _since(since), {}
    for r in self.of('touch'):
        if (r.get('at') or 0) < after: continue
        seen[r.path] = max(seen.get(r.path, 0), r.get('at') or 0)
    return L(sorted(seen.items(), key=lambda kv: -kv[1])[:int(limit)])

# %% ../nbs/00_core.ipynb #43957fae
@patch
def search(self:Ledger, query, limit=20):
    "Sessions whose prompt, title or touched paths mention `query`."
    q = str(query).lower()
    hits = {r.session for r in self.of('touch') if q in str(r.get('path', '')).lower()}
    out = []
    for row in fold(self.of('session')):
        blob = ' '.join(str(row.get(k, '')) for k in ('prompt', 'title', 'model', 'harness'))
        if q in blob.lower() or row.session in hits: out.append(row)
    return L(out).sorted(key=lambda r: r.get('started') or 0, reverse=True)[:int(limit)]


@patch
def detail(self:Ledger, record_id):
    "The machine-local half of one record: whole arguments, whole output, exact changed lines."
    for r in self.all(DETAIL):
        if r.id == record_id: return r
    return None


@patch
def stats(self:Ledger):
    "What this ledger holds."
    kinds = {}
    for r in self.all(): kinds[r.kind] = kinds.get(r.kind, 0) + 1
    rows = fold(self.of('session'))
    return AttrDict(path=str(self.home.path), records=len(self.all()), sessions=len(rows),
                    harnesses=sorted({r.get('harness', '') for r in rows} - {''}),
                    files=len({r.path for r in self.of('touch')}),
                    detail=len(self.all(DETAIL)), **kinds)
