"""Did the change land, and if not, what happened to it.

Docs: https://vedicreader.github.io/panjika/git.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_git.ipynb.

# %% auto #0
__all__ = ['STATES', 'EVIDENCE', 'UNCOMMITTED', 'Verdict', 'blame_rows', 'commit_row', 'match_lines', 'local_branches',
           'lines_on', 'surviving_branches', 'verdict_for', 'landed', 'report', 'link_commit', 'blend']

# %% ../nbs/03_git.ipynb #28120a95
from dataclasses import dataclass, field
from pathlib import Path

from fastcore.basics import AttrDict, patch
from fastcore.foundation import L
from gheasy.repo import GitError, GitRepo

from .core import DETAIL, Home, file_hash, fold, git_root, hashed, now
from .read import Ledger, _since

# %% ../nbs/03_git.ipynb #325bf7eb
STATES = ('landed', 'partly_landed', 'pending', 'replaced', 'gone', 'untracked',
          'uncertain', 'unknown')
EVIDENCE = ('lines', 'path', 'none')

UNCOMMITTED = '0' * 40

# %% ../nbs/03_git.ipynb #34c89b6f
@dataclass
class Verdict:
    "What became of one session's change to one file."
    path: str
    state: str = 'unknown'
    why: str = ''
    kept: int = 0
    total: int = 0
    evidence: str = 'none'
    session: str = ''
    action: str = 'edit'
    commits: list = field(default_factory=list)
    branch: str = ''
    branch_gone: bool = False
    elsewhere: list = field(default_factory=list)

    @property
    def done(self):
        "Whether the change is in the history and needs nothing further."
        return self.state == 'landed'

    @property
    def anywhere(self):
        "Whether the lines are still somewhere in this repository."
        return self.state in ('landed', 'partly_landed', 'pending') or bool(self.elsewhere)

    @property
    def survived(self):
        "The share of the lines this session wrote that are still in the file."
        return 0.0 if not self.total else round(self.kept / self.total, 3)

    def line(self):
        "One line, for a terminal or a tool result."
        share = '' if not self.total else f'  {self.kept}/{self.total} lines'
        return f'{self.state:<14} {self.path}{share}  {self.why}'.rstrip()

    def dict(self):
        "The verdict as a record, with the computed fields spelled out."
        return AttrDict(self.__dict__ | {'survived': self.survived, 'anywhere': self.anywhere})

# %% ../nbs/03_git.ipynb #973bde09
def blame_rows(repo, path):
    "Every line of `path` with the commit that owns it, or `None` when git will not blame it."
    try: return repo.blame(str(path))
    except (GitError, Exception): return None


def commit_row(repo, oid, cache=None):
    "One commit as the few fields a verdict quotes."
    if cache is not None and oid in cache: return cache[oid]
    try:
        d = repo.commit_detail(oid)
        row = AttrDict(sha=d['oid'], short=d['short'], subject=d['message'].splitlines()[0][:120],
                       author=d['author'], at=d['timestamp'])
    except Exception:
        row = AttrDict(sha=oid, short=oid[:7], subject='', author='', at=0)
    if cache is not None: cache[oid] = row
    return row


def match_lines(wanted, rows):
    "Pair each recorded line hash with an unclaimed line of the file that hashes the same."
    pool = {}
    for r in rows: pool.setdefault(hashed(r.get('text', '')), []).append(r)
    found, missing = [], 0
    for h in wanted:
        bucket = pool.get(h)
        if bucket: found.append(bucket.pop(0))
        else: missing += 1
    return found, missing

# %% ../nbs/03_git.ipynb #99618578
def local_branches(repo):
    "Every local branch name."
    try: out = repo.run('for-each-ref', '--format=%(refname:short)', 'refs/heads/')
    except Exception: return []
    return [b.strip() for b in out.splitlines() if b.strip()]


def lines_on(repo, branch, path, wanted):
    "How many of the recorded line hashes `path` still holds on `branch`."
    try: text = repo.run('show', f'{branch}:{path}')
    except Exception: return 0
    pool = {}
    for line in text.splitlines():
        h = hashed(line)
        pool[h] = pool.get(h, 0) + 1
    kept = 0
    for h in wanted:
        if pool.get(h): pool[h] -= 1; kept += 1
    return kept


def surviving_branches(repo, path, wanted, skip=''):
    "The branches, other than `skip`, holding every line the session wrote."
    if not wanted: return []
    return [b for b in local_branches(repo)
            if b != skip and lines_on(repo, b, path, wanted) == len(wanted)]


def _head_branch(repo):
    "The branch checked out now, or `''` on a detached HEAD."
    try: name = repo.run('rev-parse', '--abbrev-ref', 'HEAD').strip()
    except Exception: return ''
    return '' if name == 'HEAD' else name


def _wanted(ledger, touches):
    "Every line hash the session recorded for one path, oldest touch first."
    return [h for t in touches for h in ((ledger.detail(t.id) or {}).get('lines') or ())]

# %% ../nbs/03_git.ipynb #f426c635
def _replaced_by(repo, path, after):
    "The commits on this branch that touched `path` after a session did, newest first."
    try: rows = repo.history(limit=20, ref='HEAD', path=str(path))
    except Exception: return []
    return [r for r in rows if (r.get('timestamp') or 0) >= after - 1]


def _coarse(repo, touch, root, why_extra='', after=None):
    "The verdict when the machine-local tier is not here to say which lines were written."
    path = touch.path
    after = touch.get('at') or 0 if after is None else after
    later = _replaced_by(repo, path, after)
    v = Verdict(path=path, session=touch.session, action=touch.get('action', 'edit'),
                evidence='path', commits=[AttrDict(sha=c['oid'], short=c['short'],
                                                   subject=c['subject'], author=c['author'],
                                                   at=c['timestamp']) for c in later])
    if later:
        v.state = 'uncertain'
        v.why = (f'{len(later)} commit(s) touched this file afterwards, but no line record is '
                 'here to say whether this change is still in it. Read the commits, or run '
                 'where the session ran.')
        return v
    if file_hash(root/path) == touch.get('after'):
        v.state, v.why = 'pending', 'the file is byte-for-byte what the session left, and nothing has been committed'
        return v
    v.state = 'unknown'
    v.why = ('no line record and no commit since. ' + why_extra).strip()
    return v

# %% ../nbs/03_git.ipynb #69e9a43b
def verdict_for(ledger,
                touches,        # every touch that session made to one path
                repo=None,      # the repository, built from `root` when absent
                root=None,      # the repository root, taken from `repo` when absent
                cache=None,     # a commit-row cache shared across one `landed` call
                branch=''):     # the branch the session ran on
    "What became of a session's whole change to one file."
    if not isinstance(touches, (list, tuple, L)): touches = [touches]
    touches = sorted(touches, key=lambda t: t.get('at') or 0)
    touch, branch = touches[-1], str(branch or '')
    root = Path(root or repo.root)
    repo = repo or GitRepo(root)
    path, action = touch.path, touch.get('action', 'edit')
    target, after = root/path, touches[0].get('at') or 0
    wanted, here = _wanted(ledger, touches), _head_branch(repo)
    gone = bool(branch) and branch != here and branch not in local_branches(repo)

    def out(v):
        v.branch, v.branch_gone = branch, gone
        if v.state in ('replaced', 'gone') and v.total:
            v.elsewhere = surviving_branches(repo, path, wanted, here)
            if v.elsewhere: v.why += f'; still on {", ".join(v.elsewhere)}'
            else: v.why += '; and on no other branch either'
        if gone and v.state != 'landed':
            v.why = f'{v.why}; the branch {branch} it ran on is gone'.lstrip('; ')
        return v

    if not target.exists():
        gone_in = _replaced_by(repo, path, after)
        if action == 'delete' and gone_in:
            return out(Verdict(path, 'landed', 'the deletion is in the history', evidence='path',
                               session=touch.session, action=action,
                               commits=[commit_row(repo, c['oid'], cache) for c in gone_in[:1]]))
        return out(Verdict(path, 'gone', 'the file is not in the working tree', evidence='none',
                           session=touch.session, action=action, total=len(wanted)))
    if not touch.get('tracked', True) and not _replaced_by(repo, path, after):
        return out(Verdict(path, 'untracked', 'git is not tracking this file, so nothing can land',
                           evidence='none', session=touch.session, action=action))
    rows = blame_rows(repo, path)
    if rows is None: return out(_coarse(repo, touch, root, 'git would not blame this path', after))
    if not wanted: return out(_coarse(repo, touch, root, 'the session recorded no added lines', after))

    found, missing = match_lines(wanted, rows)
    kept, total = len(found), len(wanted)
    oids = [r['oid'] for r in found]
    committed = sorted({o for o in oids if o != UNCOMMITTED})
    waiting = sum(1 for o in oids if o == UNCOMMITTED)
    commits = [commit_row(repo, o, cache) for o in committed]
    v = Verdict(path=path, session=touch.session, action=action, kept=kept, total=total,
                evidence='lines', commits=commits)
    if kept == 0:
        later = _replaced_by(repo, path, after)
        who = f'; {later[0]["short"]} {later[0]["subject"][:60]!r} by {later[0]["author"]} owns it now' if later else ''
        v.state, v.why = 'replaced', f'none of the {total} lines this session wrote are in the file{who}'
        v.commits = [commit_row(repo, later[0]['oid'], cache)] if later else []
    elif not committed:
        v.state, v.why = 'pending', f'all {kept} surviving lines are uncommitted in the working tree'
    elif kept < total:
        v.state = 'partly_landed'
        v.why = f'{total - kept} of {total} lines are gone; the rest are in ' \
                f'{", ".join(c.short for c in commits)}'
    elif waiting:
        v.state = 'partly_landed'
        v.why = f'{waiting} of {total} lines are still uncommitted; the rest are in ' \
                f'{", ".join(c.short for c in commits)}'
    else:
        v.state = 'landed'
        v.why = f'all {total} lines are in {", ".join(c.short for c in commits)}'
    return out(v)

# %% ../nbs/03_git.ipynb #07be1d6e
def landed(session=None, path='', home=None, start='.', ledger=None):
    "What became of what was written, as one `Verdict` per file. Answers for the newest session by default."
    led = ledger or Ledger(home, start)
    root = git_root(led.home.root) or git_root(start)
    if root is None: return L()
    repo, cache = GitRepo(root), {}
    on = {r.session: r.get('branch') or '' for r in fold(led.of('session'))}
    if path and not session:
        groups = [[t for t in led.of('touch') if t.session == r.session and t.get('path') == path]
                  for r in led.trail(path)]
    else:
        if session in (None, '', 'latest'):
            rows = led.sessions(limit=1)
            if not rows: return L()
            session = rows[0].session
        by_path = {}
        for t in led.of('touch'):
            if t.session != session: continue
            if path and t.get('path') != path: continue
            by_path.setdefault(t.path, []).append(t)
        groups = list(by_path.values())
    return L(verdict_for(led, g, repo, root, cache, on.get(g[0].session, '')) for g in groups if g)


def report(session=None, path='', home=None, start='.', ledger=None):
    "The same answers as one row a model can read, plus the counts."
    vs = landed(session, path, home, start, ledger)
    counts = {}
    for v in vs: counts[v.state] = counts.get(v.state, 0) + 1
    order = ' · '.join(f'{n} {s}' for s, n in sorted(counts.items(), key=lambda kv: -kv[1]))
    return AttrDict(verdicts=vs, counts=counts, summary=order or 'nothing recorded',
                    text='\n'.join(v.line() for v in vs) or 'nothing recorded')

# %% ../nbs/03_git.ipynb #1dca0543
def link_commit(sha='HEAD', home=None, start='.', lookback='7d'):
    "Record `sha` against every session that recently touched a file in it. Returns those sessions."
    from panjika.write import Scribe
    led = Ledger(home, start)
    root = git_root(led.home.root) or git_root(start)
    if root is None: return L()
    repo = GitRepo(root)
    try: d = repo.commit_detail(sha)
    except Exception: return L()
    files = [ln.split()[0] for ln in repo.run('show', '--name-only', '--format=', d['oid']).splitlines() if ln.strip()]
    if not files: return L()
    after, seen = _since(lookback), {}
    for r in led.of('touch'):
        if r.get('path') in files and (r.get('at') or 0) >= after: seen[r.session] = r.at
    already = {(c.session, c.get('sha')) for c in led.of('commit')}
    out = L()
    for sid in seen:
        if (sid, d['oid']) in already: continue
        Scribe(home=led.home, session=sid, start=start, detail=False).commit(
            d['oid'], subject=d['message'].splitlines()[0], author=d['author'],
            files=files, branch=repo.run('rev-parse', '--abbrev-ref', 'HEAD').strip())
        out.append(sid)
    return out

# %% ../nbs/03_git.ipynb #2539a4ed
def blend(path, home=None, start='.', ledger=None, limit=60):
    "The commits and the agent sessions for one file, newest first, on one list."
    led = ledger or Ledger(home, start)
    root = git_root(led.home.root) or git_root(start)
    out = L()
    for row in led.trail(path, limit=limit):
        out.append(AttrDict(kind='session', at=row.at, session=row.session,
                            harness=row.get('harness', ''), model=row.get('model', ''),
                            branch=row.get('branch', ''),
                            title=row.get('title') or row.get('prompt', ''),
                            added=row.touch.get('added', 0), removed=row.touch.get('removed', 0)))
    if root is not None:
        try: rows = GitRepo(root).history(limit=limit, path=str(path))
        except Exception: rows = []
        for c in rows:
            out.append(AttrDict(kind='commit', at=c['timestamp'], sha=c['oid'], short=c['short'],
                                title=c['subject'], author=c['author']))
    return out.sorted(key=lambda r: (int(r.at), r.kind == 'commit'), reverse=True)[:int(limit)]
