"""Getting the record out of whichever agent is running.

Docs: https://vedicreader.github.io/panjika/harness.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_harness.ipynb.

# %% auto #0
__all__ = ['PATH_KEYS', 'TARGET_KEYS', 'CODEX_EDITS', 'ADAPTERS', 'CC_EVENTS', 'POST_COMMIT', 'CODEX_EVENTS', 'CODEX_TRUST',
           'CODEX_SNIPPET', 'SKILL_DIRS', 'plan', 'act', 'first_of', 'tool_target', 'tool_path', 'claude_code',
           'patch_paths', 'codex_paths', 'codex', 'codex_notify', 'ramabana', 'generic', 'ingest', 'hook',
           'codex_hooks', 'cc_settings', 'skill_md', 'skill_body', 'write_skill', 'install']

# %% ../nbs/04_harness.ipynb #c9717a73
import json, os, re, sys
from importlib.resources import files
from pathlib import Path

from fastcore.basics import AttrDict
from fastcore.foundation import L

from .core import Home, now
from .write import Scribe, action_for, repo_facts

# %% ../nbs/04_harness.ipynb #322cecdf
def plan(session='', start='', **acts):
    "Empty plan for one session."
    return AttrDict(session=str(session or ''), start=str(start or ''), acts=L(), **acts)


def act(p, do, **kw):
    "Add one call to a plan. `do` names a `Scribe` method."
    p.acts.append(AttrDict(do=do, **kw))
    return p


def first_of(d, *keys, default=''):
    "The first key present and non-empty in `d`."
    for k in keys:
        v = (d or {}).get(k)
        if v not in (None, '', [], {}): return v
    return default

# %% ../nbs/04_harness.ipynb #98927de1
PATH_KEYS = ('file_path', 'filePath', 'notebook_path', 'notebookPath', 'path', 'filename', 'file')

TARGET_KEYS = ('command', 'url', 'pattern', 'query', 'prompt', 'description', 'code')


def tool_target(args):
    "The one thing a tool call was pointed at: a path, else a command, a url, a pattern."
    return str(first_of(args, *PATH_KEYS, *TARGET_KEYS))


def tool_path(args):
    "The file a tool call names, or `''`."
    return str(first_of(args, *PATH_KEYS))

# %% ../nbs/04_harness.ipynb #d66caa75
def claude_code(payload):
    "One Claude Code hook payload as a plan. See the hooks reference for the field names."
    p = payload or {}
    event = str(p.get('hook_event_name') or '')
    out = plan(p.get('session_id'), p.get('cwd'))
    args = p.get('tool_input') or {}
    tool = str(p.get('tool_name') or '')
    if event == 'SessionStart':
        act(out, 'begin', harness='claude-code', model=str(p.get('model') or ''),
            agent=str(p.get('agent_type') or ''), parent=str(p.get('agent_id') and p.get('session_id') or ''))
    elif event == 'UserPromptSubmit':
        text = str(first_of(p, 'user_input', 'prompt'))
        act(out, 'note', text=text)
        act(out, 'write', kind='session', prompt=text[:2000])
    elif event in ('PostToolUse', 'PostToolUseFailure'):
        ok = event == 'PostToolUse'
        act(out, 'step', tool=tool, target=tool_target(args), ok=ok, args=args,
            output=p.get('tool_response'), summary='' if ok else 'the tool failed')
        path = tool_path(args)
        if ok and path and action_for(tool) == 'write':
            act(out, 'touch', path=path, action='edit')
    elif event in ('Stop', 'SubagentStop'):
        last = str(p.get('last_assistant_message') or '')
        if last: act(out, 'note', text=last[:4000])
    elif event == 'SessionEnd':
        act(out, 'end', status='done', reason=str(p.get('reason') or ''))
    return out

# %% ../nbs/04_harness.ipynb #f49bf0ab
CODEX_EDITS = ('apply_patch', 'Edit', 'Write')
_PATCH_FILE = re.compile(r'^\*\*\* (?:Add|Update|Delete) File: (.+)$', re.M)


def patch_paths(text):
    "The files an `apply_patch` envelope names."
    return [m.group(1).strip() for m in _PATCH_FILE.finditer(str(text or ''))]


def codex_paths(tool, args):
    "The files one Codex tool call moved."
    if tool in CODEX_EDITS:
        body = first_of(args, 'command', 'input', 'patch', 'content')
        if (found := patch_paths(body)): return found
    path = tool_path(args)
    return [path] if path and action_for(tool) == 'write' else []


def _codex_failed(response):
    "Whether a `tool_response` reports an error. Codex has no separate failure event."
    if isinstance(response, dict):
        return bool(response.get('isError') or response.get('is_error') or response.get('error'))
    return False


def codex(payload):
    "One Codex lifecycle-hook payload as a plan."
    p = payload or {}
    event = str(p.get('hook_event_name') or '')
    out = plan(p.get('session_id'), p.get('cwd'))
    args = p.get('tool_input') or {}
    tool = str(p.get('tool_name') or '')
    agent = str(p.get('agent_type') or p.get('agent_id') or '')
    if event in ('SessionStart', 'SubagentStart'):
        act(out, 'begin', harness='codex', model=str(p.get('model') or ''), agent=agent,
            parent=str(p.get('session_id') or '') if p.get('agent_id') else '')
    elif event == 'UserPromptSubmit':
        text = str(first_of(p, 'prompt', 'user_input', 'user_prompt'))
        act(out, 'note', text=text)
        act(out, 'write', kind='session', prompt=text[:2000], origin='human')
    elif event == 'PostToolUse':
        resp = p.get('tool_response')
        ok = not _codex_failed(resp)
        act(out, 'step', tool=tool, target=tool_target(args), ok=ok, args=args, output=resp,
            summary='' if ok else 'the tool reported an error')
        if ok:
            for path in codex_paths(tool, args): act(out, 'touch', path=path, action='edit')
    elif event in ('Stop', 'SubagentStop'):
        text = str(first_of(p, 'last_assistant_message', 'last-assistant-message'))
        if text: act(out, 'note', text=text[:4000])
    elif event == 'SessionEnd':
        act(out, 'end', status='done', reason=str(p.get('reason') or ''))
    return out


def codex_notify(payload):
    "One legacy Codex `notify` payload as a plan."
    p = payload or {}
    if str(p.get('type') or '') != 'agent-turn-complete': return plan('', '')
    out = plan(first_of(p, 'thread-id', 'turn-id'), str(p.get('cwd') or ''))
    act(out, 'begin', harness='codex', model='', title=str(p.get('client') or ''))
    for text in (p.get('input-messages') or []):
        act(out, 'write', kind='session', prompt=str(text)[:2000], origin='human')
    if (last := p.get('last-assistant-message')): act(out, 'note', text=str(last)[:4000])
    act(out, 'end', status='turn-complete', turn=str(p.get('turn-id') or ''))
    return out

# %% ../nbs/04_harness.ipynb #a97f15bb
def ramabana(payload):
    "One Ramabana turn record as a plan, or one `Act` on its own as one step."
    p = payload or {}
    out = plan(first_of(p, 'session', 'session_id'), first_of(p, 'cwd', 'root'))
    if not any(p.get(k) for k in ('activity', 'prompt', 'reply', 'tool', 'model', 'error')):
        return out
    if p.get('tool') and 'activity' not in p:
        act(out, 'step', tool=p['tool'], target=_act_target(p), ok=bool(p.get('ok', True)),
            secs=float(p.get('secs') or 0), summary=str(p.get('summary') or ''),
            args=p.get('args'), output=p.get('detail'))
        if _act_path(p): act(out, 'touch', path=_act_path(p), action='edit')
        return out
    usage, at = p.get('usage') or {}, p.get('at')
    act(out, 'write', kind='session', harness='ramabana', model=str(p.get('model') or ''),
        prompt=str(p.get('prompt') or '')[:2000], status=str(p.get('state') or 'done'),
        at=at, started=at,
        tokens_in=usage.get('input'), tokens_out=usage.get('output'), cost=usage.get('cost'))
    for a in (p.get('activity') or ()):
        act(out, 'step', tool=str(a.get('tool') or ''), target=_act_target(a),
            ok=bool(a.get('ok', True)), secs=float(a.get('secs') or 0),
            summary=str(a.get('summary') or ''), args=a.get('args'), output=a.get('detail'))
        if a.get('ok', True) and _act_path(a): act(out, 'touch', path=_act_path(a), action='edit')
    if p.get('reply'): act(out, 'note', text=str(p['reply'])[:4000])
    if p.get('error'): act(out, 'note', text=f"failed: {p['error']}")
    return out


def _act_target(a): return tool_target(a.get('args') or {}) or str(a.get('summary') or '')


def _act_path(a):
    "The file a Ramabana act names, when the tool it ran was one that writes."
    path = tool_path(a.get('args') or {})
    return path if path and action_for(a.get('tool') or '') == 'write' else ''


# %% ../nbs/04_harness.ipynb #d176cda8
def generic(payload):
    "A payload that already speaks the ledger's own shape, as one act or a list under `acts`."
    p = dict(payload or {})
    out = plan(first_of(p, 'session', 'session_id'), first_of(p, 'cwd', 'start'))
    acts = p.get('acts')
    if acts is None:
        do = p.pop('do', None)
        for k in ('session', 'session_id', 'cwd', 'start', 'harness_name'): p.pop(k, None)
        if not do and not p: return out
        acts = [{'do': do or 'note', **p}]
    for a in acts:
        a = dict(a)
        act(out, a.pop('do', 'note'), **a)
    return out


ADAPTERS = {'claude-code': claude_code, 'codex': codex, 'codex-notify': codex_notify, 'ramabana': ramabana,
            'generic': generic}

# %% ../nbs/04_harness.ipynb #061d9533
def ingest(payload, adapter='generic', home=None, start='.', harness=''):
    "Apply one payload to a ledger. Returns the plan that was applied."
    build = ADAPTERS.get(str(adapter), generic)
    p = build(payload)
    if not p.acts:
        p.wrote, p.home = 0, ''
        return p
    sc = Scribe(home=home, session=p.session, start=p.start or start)
    if not sc.home.exists: sc.home.init()
    facts = None
    for a in p.acts:
        do = a.pop('do')
        if do == 'begin': a.setdefault('harness', harness or str(adapter))
        elif do == 'write' and a.get('kind') == 'session' and 'branch' not in a:
            if facts is None: facts = repo_facts(sc.start)
            a = {**facts, **a}
        getattr(sc, do)(**a)
    p.wrote, p.home, p.session = len(p.acts), str(sc.home.path), sc.session
    return p


def hook(adapter='generic', stream=None, home=None, start=None):
    "Read one payload from `stream` and record it. Never raises; failures go to stderr."
    try:
        raw = (stream or sys.stdin).read()
        payload = json.loads(raw) if raw.strip() else {}
    except Exception as e:
        print(f'panjika: unreadable payload ({e})', file=sys.stderr)
        return None
    if not payload: return None
    try: return ingest(payload, adapter, home, start or payload.get('cwd') or os.getcwd())
    except Exception as e:
        print(f'panjika: {type(e).__name__}: {e}', file=sys.stderr)
        return None

# %% ../nbs/04_harness.ipynb #252f8ebe
CC_EVENTS = {'SessionStart': '', 'UserPromptSubmit': '', 'SessionEnd': '',
             'PostToolUse': '*', 'PostToolUseFailure': '*'}

POST_COMMIT = """#!/bin/sh
# Written by `panjika install --git`. Links each commit to the agent sessions that earned it.
panjika link-commit "$(git rev-parse HEAD)" >/dev/null 2>&1 || true
"""

CODEX_EVENTS = {'SessionStart': '', 'UserPromptSubmit': '', 'SessionEnd': '',
                'PostToolUse': '.*', 'SubagentStart': '', 'SubagentStop': ''}

CODEX_TRUST = ("Codex will not run a hook until you have reviewed it. Run `/hooks` in Codex, "
               "read the entry, and trust it.")

CODEX_SNIPPET = """# ~/.codex/config.toml
# Only for a Codex without lifecycle hooks. One record per turn, no tool calls.
notify = ["panjika", "record", "--adapter", "codex-notify"]
"""


def codex_hooks(path='.codex/hooks.json', command='panjika hook codex'):
    "The Codex hooks document with panjika's hooks merged into it."
    p = Path(path)
    try: doc = json.loads(p.read_text()) if p.exists() else {}
    except Exception: doc = {}
    if not isinstance(doc, dict): doc = {}
    hooks = doc.setdefault('hooks', {})
    for event, matcher in CODEX_EVENTS.items():
        groups = [g for g in hooks.get(event, [])
                  if not any('panjika' in str(h.get('command', ''))
                             for h in (g.get('hooks') or []))]
        group = {'hooks': [{'type': 'command', 'command': command, 'timeout': 10}]}
        if matcher: group['matcher'] = matcher
        hooks[event] = groups + [group]
    return doc


def cc_settings(path='.claude/settings.json', command='panjika hook claude-code'):
    "The Claude Code settings document with panjika's hooks merged into it."
    p = Path(path)
    try: doc = json.loads(p.read_text()) if p.exists() else {}
    except Exception: doc = {}
    if not isinstance(doc, dict): doc = {}
    hooks = doc.setdefault('hooks', {})
    for event, matcher in CC_EVENTS.items():
        entries = [e for e in hooks.get(event, [])
                   if not any('panjika' in str(h.get('command', ''))
                              for h in (e.get('hooks') or []))]
        entry = {'hooks': [{'type': 'command', 'command': command, 'timeout': 10}]}
        if matcher: entry['matcher'] = matcher
        hooks[event] = entries + [entry]
    return doc

# %% ../nbs/04_harness.ipynb #dfaccb42
SKILL_DIRS = ('.claude/skills/panjika', '.agents/skills/panjika', '.codex/skills/panjika')


def skill_md():
    "The packaged `SKILL.md`, frontmatter and all."
    return (files('panjika')/'SKILL.md').read_text(encoding='utf-8')


def skill_body(text=None):
    "A skill document without its YAML frontmatter."
    text = skill_md() if text is None else text
    if not text.startswith('---'): return text
    end = text.find('\n---', 3)
    return text if end < 0 else text[end + 4:].lstrip('\n')


def write_skill(root='.', dirs=SKILL_DIRS):
    "Write the packaged skill into each agent's skill folder under `root`. Returns the paths."
    body, out = skill_md(), L()
    for d in dirs:
        p = Path(root)/d/'SKILL.md'
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
        out.append(str(p))
    return out

# %% ../nbs/04_harness.ipynb #81145f9a
def install(root='.', claude_code=True, git=True, codex=True, skill=True, home=None):
    "Write the hook configuration and the skill into `root`. Returns what was written and what was not."
    root = Path(root)
    out, ledger = AttrDict(wrote=L(), skipped=L(), codex=CODEX_SNIPPET,
                           note=CODEX_TRUST), Home(home, root)
    ledger.init()
    out.home = str(ledger.path)
    if claude_code:
        p = root/'.claude'/'settings.json'
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(cc_settings(p), indent=2) + '\n')
        out.wrote.append(str(p))
    if codex:
        p = root/'.codex'/'hooks.json'
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(codex_hooks(p), indent=2) + '\n')
        out.wrote.append(str(p))
    if skill: out.wrote += write_skill(root)
    if git:
        from panjika.core import git_root
        gr = git_root(root)
        if gr is None: out.skipped.append('post-commit: not inside a git repository')
        else:
            p = Path(gr)/'.git'/'hooks'/'post-commit'
            if p.exists() and 'panjika' not in p.read_text():
                out.skipped.append(f'post-commit: {p} exists and is not ours')
            else:
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(POST_COMMIT)
                p.chmod(0o755)
                out.wrote.append(str(p))
    return out
