"""the skill, for a harness that reads skills from packages

Docs: https://vedicreader.github.io/panjika/skill.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_skill.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/07_skill.ipynb #701281c1
from .harness import skill_body

__doc__ = skill_body()
