"""Appending to a ledger. One call, one line, no lock.

Docs: https://vedicreader.github.io/panjika/write.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_write.ipynb.

# %% auto #0
__all__ = ['ACTION_HINTS', 'ACTIONS', 'action_for', 'Scribe', 'repo_facts', 'text_changes', 'diff_lines', 'body_lines',
           'head_hash']

# %% ../nbs/01_write.ipynb #c54d5834
import re
from pathlib import Path

from fastcore.basics import AttrDict, ifnone

from fastcore.basics import patch

from gheasy.repo import GitRepo

from .core import (DETAIL, LEDGER, MAX_DETAIL, Home, append, file_hash, git_root, hashed,
                   new_id, now)

# %% ../nbs/01_write.ipynb #78c18ffd
ACTION_HINTS = (
    ('write', ('edit', 'write', 'patch', 'create', 'apply', 'update', 'insert', 'replace', 'delete')),
    ('run',   ('bash', 'shell', 'exec', 'run', 'terminal', 'command', 'python', 'notebook_run')),
    ('net',   ('web', 'fetch', 'url', 'browser', 'http', 'research', 'crawl')),
    ('search',('grep', 'search', 'glob', 'find', 'index', 'similar', 'outline', 'symbols')),
    ('read',  ('read', 'view', 'cat', 'open', 'ls', 'list', 'show', 'inspect', 'vars')),
    ('plan',  ('todo', 'plan', 'task')),
    ('ask',   ('ask', 'approval', 'question', 'permission')),
)

ACTIONS = ('write', 'run', 'net', 'search', 'read', 'plan', 'ask', 'other')


def action_for(tool):
    "Which of `ACTIONS` a tool name means. `other` when nothing matches."
    name = str(tool or '').lower()
    for action, hints in ACTION_HINTS:
        if any(h in name for h in hints): return action
    return 'other'

# %% ../nbs/01_write.ipynb #00ebba70
def _target(value, n=160):
    "The one-line target of a step: a path, a command, a url, whatever it was pointed at."
    return ' '.join(str(value or '').split())[:n]


class Scribe:
    "Appends to one ledger."

    def __init__(self,
                 home=None,         # the ledger folder. None finds one from `start`
                 session='',        # the session every record joins. None starts a fresh id
                 start='.',         # where to look for a ledger, and the repository to describe
                 detail=True):      # write the machine-local tier as well as the committed one
        self.home = home if isinstance(home, Home) else Home(home, start)
        self.session = str(session or new_id('s-'))
        self.start, self.detail = str(start), bool(detail)
        self._seq = 0

    def __repr__(self): return f'Scribe({self.session} -> {self.home.path})'

    def write(self, kind, detail=None, **fields):
        "Append one record. `detail` goes to the machine-local tier under the same id."
        rec = {'kind': kind, 'id': fields.pop('id', None) or new_id(),
               'at': fields.pop('at', None) or now(),
               'session': fields.pop('session', None) or self.session, **fields}
        rec = {k: v for k, v in rec.items() if v is not None}
        out = append(self.home.shard(LEDGER, rec['at']), rec)
        if detail and self.detail:
            append(self.home.shard(DETAIL, rec['at']),
                   {'kind': kind, 'id': rec['id'], 'at': rec['at'], 'session': rec['session'], **detail},
                   MAX_DETAIL)
        return out

# %% ../nbs/01_write.ipynb #64de29d0
def repo_facts(start='.'):
    "The repository name, root and current branch for `start`, as far as they can be told."
    root = git_root(start)
    branch = ''
    if root is not None:
        try: branch = GitRepo(root).run('rev-parse', '--abbrev-ref', 'HEAD').strip()
        except Exception: branch = ''
    return {'repo': root.name if root else '', 'root': str(root) if root else '',
            'branch': '' if branch == 'HEAD' else branch}

# %% ../nbs/01_write.ipynb #019f681e
@patch
def begin(self:Scribe, harness, model='', prompt='', title='', parent='', agent='', **fields):
    "Record that a session started. Returns its id."
    self.write('session', harness=str(harness), model=str(model or ''),
               prompt=_target(prompt, 2000), title=str(title or ''), status='open',
               parent=str(parent or ''), agent=str(agent or ''),
               started=fields.pop('started', None) or fields.get('at') or now(),
               cwd=str(Path(self.start).resolve()), **repo_facts(self.start), **fields)
    return self.session


@patch
def end(self:Scribe, status='done', **fields):
    "Record that a session finished, with whatever counters the harness can supply."
    return self.write('session', status=str(status),
                      ended=fields.pop('ended', None) or fields.get('at') or now(), **fields)

# %% ../nbs/01_write.ipynb #698f896d
@patch
def step(self:Scribe, tool, target='', ok=True, secs=0.0, action='', summary='',
         args=None, output=None, **fields):
    "Record one tool call. Returns the step id."
    self._seq += 1
    detail = None
    if args is not None or output is not None:
        detail = {'tool': str(tool), 'args': args, 'output': None if output is None else str(output)}
    rec = self.write('step', detail=detail, tool=str(tool), seq=self._seq,
                     action=action or action_for(tool), target=_target(target),
                     ok=bool(ok), secs=round(float(secs or 0), 3),
                     summary=_target(summary, 300), **fields)
    return rec.id


@patch
def note(self:Scribe, text, **fields):
    "Record a line of prose against the session: a plan, a summary, a reason."
    return self.write('note', text=str(text)[:4000], **fields).id

# %% ../nbs/01_write.ipynb #cefd6416
def text_changes(before, after):
    "The lines `after` adds to `before` and the ones it drops, for a change git cannot be asked about."
    import difflib
    b, a = (before or '').splitlines(), (after or '').splitlines()
    add, rem = [], []
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, b, a).get_opcodes():
        if tag in ('replace', 'delete'): rem += b[i1:i2]
        if tag in ('replace', 'insert'): add += a[j1:j2]
    return add, rem


def diff_lines(diff):
    "The added and removed lines of a unified diff, without its headers."
    added, removed = [], []
    for line in str(diff or '').splitlines():
        if line[:4] in ('+++ ', '--- ') or line in ('+++', '---'): continue
        if line.startswith('+'): added.append(line[1:])
        elif line.startswith('-'): removed.append(line[1:])
    return added, removed


def body_lines(path):
    "Every line of a file, for a change git will not diff because it is not tracking it."
    try: return Path(path).read_text(encoding='utf-8', errors='replace').splitlines()
    except OSError: return []


def head_hash(root, path):
    "The hash of a path's committed content at HEAD, or `''` when it is not committed."
    try: return hashed(GitRepo(root).run('show', f'HEAD:{path}'))
    except Exception: return ''

# %% ../nbs/01_write.ipynb #c07d0790
@patch
def touch(self:Scribe,
          path,               # the file that moved, absolute or relative to `start`
          action='edit',      # what happened to it: edit, create, delete
          step='',            # the id of the step that did it
          before=None,        # the body before the change, for a backfill
          after_text=None,    # the body after it, for a backfill
          **fields):
    "Record that a file was touched, and how it now differs from `HEAD`."
    p = Path(path)
    root = git_root(p if p.is_absolute() else self.start)
    rel = str(p.resolve().relative_to(root)) if root and p.is_absolute() else str(path)
    ranges, added, removed, tracked = [], [], [], bool(root)
    if after_text is not None:
        added, removed = text_changes(before, after_text)
    elif root is not None:
        try:
            ch = GitRepo(root).file_changes(rel)
            ranges = [[r['from'], r['to'], r['kind']] for r in ch.get('ranges') or []]
            added, removed = diff_lines(ch.get('diff'))
            tracked = not (ch.get('status') or {}).get('untracked', False)
        except Exception: pass
    if not added and not tracked and root is not None:
        added = body_lines(p if p.is_absolute() else Path(self.start)/path)
    detail = {'path': rel, 'lines': [hashed(t) for t in added][:2000]} if added else None
    rec = self.write('touch', detail=detail, path=rel, action=str(action), step=str(step or ''),
                     head=head_hash(root, rel) if root else '',
                     after=(hashed(after_text) if after_text is not None else
                            file_hash(p if p.is_absolute() else Path(self.start)/path)),
                     added=len(added), removed=len(removed), ranges=ranges[:200],
                     tracked=tracked, **fields)
    return rec.id


@patch
def commit(self:Scribe, sha, subject='', author='', files=(), branch='', **fields):
    "Record that a commit exists and which session it belongs to."
    return self.write('commit', sha=str(sha), subject=_target(subject, 300), author=str(author or ''),
                      files=list(files)[:500], branch=str(branch or ''), **fields).id
